/**
 * SGIP — Generated API Types
 * Ticket: SGIP-1.2.2.3
 *
 * ⚠️  AUTO-GENERATED FILE — DO NOT EDIT MANUALLY
 *
 * This file is generated by running:
 *   pnpm --filter @sgip/web run api:generate-types
 *
 * Which calls:
 *   npx openapi-typescript http://localhost:4000/api/v1/openapi-json -o src/lib/api/api.types.ts
 *
 * For Phase 1, this is hand-authored to match the /health endpoint exactly.
 * Once the NestJS API is running, regenerate with the above command and this file
 * will be replaced with the complete type tree.
 *
 * Generated from: NestJS Swagger spec (Document 2 §8.3)
 * API Version: 0.1.0
 */

export interface paths {
  '/health': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['AppController_getHealth'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}

export interface operations {
  AppController_getHealth: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: Record<string, unknown>;
        content: {
          'application/json': HealthCheckResponse;
        };
      };
    };
  };
}

// ── Response types ────────────────────────────────────────────────────────────

export type OverallStatus = 'ok' | 'degraded' | 'down';
export type ComponentStatus = 'ok' | 'degraded' | 'unavailable';

export interface RedisComponentHealth {
  status: ComponentStatus;
  latencyMs?: number;
  error?: string;
}

export interface DatabaseComponentHealth {
  status: ComponentStatus;
  latencyMs?: number;
  error?: string;
}

export interface HealthCheckResponse {
  status: OverallStatus;
  timestamp: string;
  version: string;
  uptime: number;
  components: {
    database: DatabaseComponentHealth;
    redis: RedisComponentHealth;
  };
}

// ── Standard error envelope (AllExceptionsFilter, Document 2 §8.3) ────────────
export interface ApiError {
  error: {
    code: string;
    message: string;
    fieldErrors?: Record<string, string[]>;
  };
}
